#! /usr/bin/python

import os
import shutil

file_path = '/home/jkcore/core/data/treated/98888888/20180526/backdir'
new_path = '/home/jkcore/core/data/20180727'

if not os.path.isdir(new_path):
    os.makedirs(new_path)

files = os.listdir(file_path)

for file_name in files:
    file = file_name.split('.')[-1]
    oldname = os.path.join(file_path, file_name)
    newname = os.path.join(new_path, file)
    shutil.copy(oldname, newname)
    print(newname)
